name: Build a Docker image

on: [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t my-next-app .

      - name: build the Docker image
        run: docker build ./my-next-app -t charansaig1/my-next-app:latest
