name: Build a Docker image

on: [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
.

      - name: build the Docker image
        run: docker build ./my-next-app -t charansaig1/my-next-app:latest

     # Run the Docker container (to test if the app works)
     - name: Run Docker container
     run: |
       docker run -d -p 3000:3000 --name next-app-container my-next-app
       # Wait for the container to start
       sleep 10

    # Test the running container (example: test if the Next.js app is accessible)
    - name: Test the app
    run: |
      curl --fail http://localhost:3000 || exit 1
